version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:2.441-jdk17
    container_name: jenkins-ctf
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: on-failure
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins_init.groovy:/var/jenkins_home/init.groovy.d/jenkins_init.groovy
      - ./flags:/var/jenkins_home/flags
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

  web:
    image: nginx:latest
    container_name: web-ctf
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./web:/usr/share/nginx/html:ro
    depends_on:
      - jenkins

volumes:
  jenkins_home:

